### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by tcgumus** [ChristopherBiscardi/gatsby-plugin-webmention#5]
Is there any usage doc?

**Comment by Lewiscowles1986** [comment]
What about the information in README.md?

Are there specific things you feel are missing?

**Comment by tcgumus** [comment]
Hello Lewis,
I actually made it work but still think it can be more helpful if we share basic usage doc for newbies like me. I specifically struggled on garphql implementation since i had already one sql and cloudn't pass any other parameter to it. I will write an article about that and send it to you. Maybe we can use it as a basic usage doc. Thank you
